spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
